= Securing {branding} Spatial App
Copyright (c) Codice Foundation
2.7-SNAPSHOT
:imagesdir: ./images
:toc: right
:branding: DDF
:audience: Developer
:icons: font
:example-caption!:

////
Copyright (c) Codice Foundation
 
 This is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 
 This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. A copy of the GNU Lesser General Public License is distributed along with this program and can be found at <http://www.gnu.org/licenses/lgpl.html>.

////

== Overview
The DDF Spatial Application provides KML transformer and a KML network link endpoint that allows a user to generate a View-based KML Query Results Network Link.
This guide covers implementations and protocols for enhancing security.
